# Automatically create a new version/tag, if new commits are available since the last tag
name: Auto-tagger

on:
  schedule:
    - cron: '32 23 * * 2' # Every Tuesday at 23:32 https://crontab.guru/#32_23_*_*_2

jobs:
  create-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          if [[ $(git tag -l --points-at HEAD) = "" ]]; then
            VER=$(npx daily-version)
            git tag $VER -m $VER
            git push origin $VER
          fi
