name: Test
on:
  - pull_request
  - push

jobs:
  Security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx lockfile-lint --path package-lock.json --validate-https

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: github-issue-link-status
          path: distribution
      - run: npx bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: a494d51041a39c608fc08180126e8a9faa8d3beb
